// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngsewtcnaiqtibfhsvqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nc2V3dGNuYWlxdGliZmhzdnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzYwMDUsImV4cCI6MjA3MDUxMjAwNX0.bJk_3tHufSbHz5yKXqepBUu9_aVYIn6-afKUkXH95ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});